apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops_a2_deployment
  labels:
    app: mlops_a2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops_a2
  template:
    metadata:
      labels:
        app: mlops_a2 
    spec:
      containers:
      - name: mlops_a2
        image: ahmedbilal54/mlops_a2:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: mlops_a2-service
spec:
  selector:
    app: mlops_a2 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110